### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unknown Syntax : "¬"

### ISSUE THREAD

**Issue by jasonkhanlar** [nirgit/simple-xml-to-json#17]
```
console.log(convertXML(await fs.promises.readFile(file, 'utf8', (err, data) => { if (err) throw err; return data; })));
```
returns error:
```
(node:1131385) UnhandledPromiseRejectionWarning: Error: Unknown Syntax : "¬"
    at Object.next (/root/node_modules/simple-xml-to-json/src/lexer.js:159:31)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:52:29)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
    at parseExpr (/root/node_modules/simple-xml-to-json/src/transpiler.js:57:39)
(node:1131385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1131385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nirgit** [comment]
should be resolved in v1.0.9
